// Writes supabase/SCHEMA.md from the live database.
//
// Why this exists. The migrations in supabase/migrations describe a fraction
// of the real database: the cards table alone has 203 columns, most of which
// appear in no migration here, alongside 62 tables, 34 RPC functions, and
// triggers and RLS policies that nothing in this repo mentions.
//
// That gap is not academic. A card created without assigned_user_id is forced
// to archived = true by a trigger, and the RLS policy that serves public cards
// filters archived rows - so the card 404s for everyone while looking healthy
// in the dashboard. That cost half a day to diagnose purely because none of
// the mechanism was readable from the code.
//
// Run: npm run schema
//
// LIMITS, and they matter. This reads PostgREST's OpenAPI description, which
// is everything the API can see: tables, columns, types, defaults, and the
// signatures of exposed functions. It cannot see triggers, RLS policies,
// indexes, check constraints or function bodies, because PostgREST does not
// expose them. For those, see the command at the top of the generated file.
import { writeFileSync, readFileSync, mkdirSync } from 'fs'
import { dirname } from 'path'

const env = Object.fromEntries(
  readFileSync('.env.local', 'utf8')
    .split('\n')
    .filter(l => l.includes('='))
    .map(l => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim().replace(/^["']|["']$/g, '')])
)

const URL_ = env.NEXT_PUBLIC_SUPABASE_URL
const KEY = env.SUPABASE_SERVICE_ROLE_KEY
if (!URL_ || !KEY) {
  console.error('dump-schema: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required in .env.local')
  process.exit(1)
}

const res = await fetch(URL_ + '/rest/v1/', {
  headers: { apikey: KEY, Authorization: 'Bearer ' + KEY, Accept: 'application/openapi+json' },
})
if (!res.ok) {
  console.error('dump-schema: could not read the schema:', res.status, await res.text())
  process.exit(1)
}
const spec = await res.json()

const tables = Object.entries(spec.definitions || {}).sort(([a], [b]) => a.localeCompare(b))
const rpcs = Object.keys(spec.paths || {}).filter(p => p.startsWith('/rpc/')).sort()

// The description PostgREST returns carries the primary key and foreign key
// notes inline; pull them out so the table reads like a schema rather than prose.
function annotate(desc = '') {
  const notes = []
  if (/Primary Key/i.test(desc)) notes.push('PK')
  const fk = desc.match(/`([a-z_]+\.[a-z_]+)`/i)
  if (/Foreign Key/i.test(desc) && fk) notes.push('FK -> ' + fk[1])
  return notes.join(', ')
}

const out = []
out.push('# Cardtly database schema')
out.push('')
out.push('Generated by `npm run schema` from the live database. Do not edit by hand.')
out.push('')
out.push('## Read this before changing the database')
out.push('')
out.push('The files in `supabase/migrations` are **not** a complete record of this')
out.push('database. Much of it was changed directly in the Supabase dashboard, so a')
out.push('column, trigger or policy can exist here and appear nowhere in the repo.')
out.push('Check this file before assuming a column does not exist.')
out.push('')
out.push('**What this file covers:** every table, column, type and default, plus the')
out.push('signatures of functions exposed over the API.')
out.push('')
out.push('**What it does not cover:** triggers, RLS policies, indexes, check')
out.push('constraints and function bodies. PostgREST cannot see them. For those you')
out.push('need a direct database connection:')
out.push('')
out.push('```')
out.push('supabase link --project-ref <ref>')
out.push('supabase db dump --schema public > supabase/schema.sql')
out.push('```')
out.push('')
out.push('That gap has already caused one production incident: a trigger forces')
out.push('`cards.archived = true` when `assigned_user_id` is null, and an RLS policy')
out.push('hides archived cards from the public, so a card 404s for every visitor while')
out.push('the dashboard still shows it as healthy. Neither is visible from this file.')
out.push('')
out.push(`## Summary`)
out.push('')
out.push(`- ${tables.length} tables`)
out.push(`- ${rpcs.length} functions exposed over the API`)
out.push(`- largest table: ${tables.map(([n, d]) => [n, Object.keys(d.properties || {}).length]).sort((a, b) => b[1] - a[1])[0].join(' with ')} columns`)
out.push('')
out.push('## Tables')
out.push('')

for (const [name, def] of tables) {
  const props = def.properties || {}
  const required = new Set(def.required || [])
  out.push(`### ${name}`)
  out.push('')
  out.push(`${Object.keys(props).length} columns`)
  out.push('')
  out.push('| column | type | null | default | notes |')
  out.push('| --- | --- | --- | --- | --- |')
  for (const [col, p] of Object.entries(props)) {
    const type = p.format || p.type || ''
    const nullable = required.has(col) ? 'no' : 'yes'
    const dflt = p.default === undefined ? '' : '`' + JSON.stringify(p.default) + '`'
    const notes = [annotate(p.description), p.description && !/Key/i.test(p.description) ? p.description.split('\n')[0].slice(0, 80) : '']
      .filter(Boolean).join(' — ')
    out.push(`| ${col} | ${type} | ${nullable} | ${dflt} | ${notes} |`)
  }
  out.push('')
}

out.push('## Functions exposed over the API')
out.push('')
for (const path of rpcs) {
  const post = spec.paths[path]?.post
  const params = post?.parameters?.[0]?.schema?.properties
  const args = params ? Object.entries(params).map(([k, v]) => `${k}: ${v.format || v.type}`).join(', ') : ''
  out.push(`- \`${path.replace('/rpc/', '')}(${args})\``)
}
out.push('')

const target = 'supabase/SCHEMA.md'
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, out.join('\n'), 'utf8')
console.log(`dump-schema: wrote ${target} - ${tables.length} tables, ${rpcs.length} functions`)
